name: docs-generator
# on: [push]
on:
  push:
    branches:
      - 'main'
jobs:
  pages-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build
      - run: git config user.email "github-actions-workflow"
      - run: git config user.name "GitHub Actions workflow"
      - run: cd ../ && git commit -am "GitHub Actions workflow build"
      - run: git push
